env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules: {
  "react/prop-types": "warn",
  "no-undef": "off",
}
