apiVersion: apps/v1
kind: Deployment
metadata:
  name: luminous-onion-dev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luminous-onion-dev
  template:
    metadata:
      labels:
        app: luminous-onion-dev
    spec:
      containers:
        - name: my-container
          image: zkarpinski/luminous-onion:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          securityContext:
            - readOnlyRootFilesystem: True
